name: CI

on:
  push:
    branches:
      - 'dev/*'
      - 'qa/*'
      - 'staging/*'
      - main

  pull_request:

jobs:

  deploy-dev:
    if: startsWith(github.ref, 'refs/heads/dev/')
    uses: eddiez0719/shared-workflows/.github/workflows/reusable-workflow2.yml@feature/create-reusable-workflows
    with:
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}